### ISSUE TITLE
Reboot and it dosn't work

### ISSUE THREAD

**Issue by CallumSnedker** [jpwilliams/midi-mixer-releases#15]
When i restart Midi-Mixer only sees focused apps in the groups pull downs and the play controles dont work 

1.Reboot and it just dosn't work 

Nothing works the only way to fix it is remove the file in Appdata/Roming

 - Version 2.4.0

**Comment by Elusivor** [comment]
You need to run it as administrator

**Comment by CallumSnedker** [comment]
Thanks
