### ISSUE TITLE
Problem with MIDI Passthru

### ISSUE THREAD

**Issue by TheAimWolf** [jpwilliams/midi-mixer-releases#16]
**Describe the bug** 

If I want to select my Akai Proffesional MidiMix as Passthru Device, I get an error:

```
Failed to set passthru device

Error invoking remote method 'setPassthruDevice': Error: Failed to open output port
```

**Screenshots**

![image](https://user-images.githubusercontent.com/60583716/132095577-3f6525cb-8dc8-40a5-8894-67ebeb3b06b5.png)

**Build (please complete the following information):**

 - 2.4.0 (Stable)

**Additional context**

Btw, love your work ;)

**Comment by jpwilliams** [comment]
If you're already using your Akai Professional MidiMix in a profile, then you won't be able to set it as a pass-thru device here. You'll need to use a program like [loopMIDI](https://www.tobias-erichsen.de/software/loopmidi.html) to send the MIDI commands to another program.

See [⚙ Settings - MIDI Mixer FAQ - MIDI Passthru](https://docs.midi-mixer.com/settings#midi-passthru) for more info. 🙂

**Comment by TheAimWolf** [comment]
Thank you, it now works like a charm.
