### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by owenworley** [jpwilliams/midi-mixer-releases#17]
Where is the source code? I only see precompiled binaries being hosted on github

**Comment by IainMNorman** [comment]
readme says: This repository is used to collate changelogs and downloads.

I believe it's not open source.

**Comment by owenworley** [comment]
Using github as a free .exe file host - love it.

**Comment by IainMNorman** [comment]
Not sure if that's sarcasm?

**Comment by owenworley** [comment]
Me neither.

**Comment by owenworley** [comment]
be me
searching for a midi volume controller on github
find one
looks good
its closed source
its abandoned
