### ISSUE TITLE
Identify Screens Button

### ISSUE THREAD

**Issue by GAndrews98** [jpwilliams/midi-mixer-releases#4]
**Is your feature request related to a problem? Please describe and link using # if you can.**
It's a minor annoyance and will only be encountered once or twice, but it would be nice if we could have a way to distinguish between different screens in the settings menu. 

**Describe the solution you'd like**
A button that would identify which monitor is which with a simple overlay like "Screen 1," "Screen 2," etc. 

**Describe alternatives you've considered**
I had to use trial and error to find which monitor corresponds to which screen (extremely minor, I know). But when you have 3 screens (or more) like I do, it would be handy. 

**Additional context**
None.

**Comment by jpwilliams** [comment]
This will be tracked in the following roadmap item: https://trello.com/c/HsBQQcY7/5-screen-identification-helper
