### ISSUE TITLE
Change the red "X" button in the Mapper

### ISSUE THREAD

**Issue by GAndrews98** [jpwilliams/midi-mixer-releases#5]
**Is your feature request related to a problem? Please describe and link using # if you can.**
When editing a button/knob/fader for a custom profile in the Mapper section of the program, the red "X" button should be modified to something else. The majority of the time I click this button instead of the back arrow to close the window, which instead deletes the item I was just modifying. This causes me to have to re-enter all the fields again. I've made this mistake more times than I've clicked the correct button. 

**Describe the solution you'd like**
Change the red "X" to a red "Delete" for clarification. 

**Describe alternatives you've considered**
Alternatively a confirmation dialog could pop up confirming that you want to delete the item. 

**Additional context**
![Annotation 2020-07-18 065338](https://user-images.githubusercontent.com/7970321/87854009-711b1680-c8c3-11ea-806c-57b80eaa0f73.png)

**Comment by jpwilliams** [comment]
You know, I've even done this myself. 😂

I'll move it elsewhere, replace the "X" with a "trash" icon, and provide a confirmation too.

Thanks for reporting these, @GAndrews98!

**Comment by jpwilliams** [comment]
Fixed in [v1.1.0](https://github.com/jpwilliams/midi-mixer-releases/releases/tag/v1.1.0).
