### ISSUE TITLE
Improve OSD visibility

### ISSUE THREAD

**Issue by RWeigelt** [jpwilliams/midi-mixer-releases#7]
When viewed from the corner of my eye, the OSD works very well on dark backgrounds, but not on light backgrounds or on some backgrounds with colored areas.

Here is an example (VS2019):
![image](https://user-images.githubusercontent.com/1882836/97999305-6f7e4b80-1deb-11eb-88f3-a91f5ddd5f0a.png)

I suggest adding a dark border:
![image](https://user-images.githubusercontent.com/1882836/97999420-92106480-1deb-11eb-9a21-9e05df59ddd2.png)
_(It does not necessarily have to be pure black as shown in the mockup)_

A shadow could be an alternative:
![image](https://user-images.githubusercontent.com/1882836/97999483-a9e7e880-1deb-11eb-960d-0005029ce2ad.png)
_(I didn't spend much time on tweaking the shadow, looks kind of "dirty" in some parts)_

Personally, I'd prefer the border, though.

**Comment by jpwilliams** [comment]
Aye I completely agree with this - I have suffered the same annoyance!

In an earlier version the OSD did actually have shadow, but this required window transparency which seemed to be causing some flickering when the OSD spawned, thus it was removed.

A border would indeed be a lovely addition. It's on my list. 👍

**Comment by jpwilliams** [comment]
@RWeigelt I've added a thin blue border to the OSD in [v2.0.8](https://github.com/jpwilliams/midi-mixer-releases/releases/tag/v2.0.8).

I tested primarily on top of browsers, but also against my own Visual Studio and it seems to be clear enough. Please feel free to re-open if it's still a bit too hard to see and we can look in to some other options (maybe pure black _is_ the way to go!).

**Comment by RWeigelt** [comment]
Hi Jack,

The blue border in 2.0.8 does not work well on darker backgrounds (I have a dark gray desktop wallpaper).

I have experimented a bit in Photoshop and included the resulting PNG files in the attached ZIP file (done quick and dirty using smart objects).
I now think a black border works best, I guess because both black and white

  *   are neutral (they don't interfere with other colors of neighboring pixels) and
  *   are at the extremes of the brightness spectrum (so you always have a sharp edge, regardless of the brightness of the background)
At first, I thought that maybe a single-pixel border would work, but on busy backgrounds a two-pixel border is better. I also tried a three-pixel border, but I don't have a real opinion on that right now (maybe I have seen too many borders).

What do you think?

Best regards
Roland

**Comment by RWeigelt** [comment]
@jpwilliams Maybe replying by email wasn't a good idea, seems like it didn't keep the attachment.
So I'll add the mockups here:

**Border two pixels wide, blue (2.0.8)**

![image](https://user-images.githubusercontent.com/1882836/98300906-43fd8b80-1fba-11eb-8953-6474c919c07e.png)

![image](https://user-images.githubusercontent.com/1882836/98300954-524ba780-1fba-11eb-9b1b-091d2228592f.png)

**Border three pixels wide, blue** 

![image](https://user-images.githubusercontent.com/1882836/98300985-5f689680-1fba-11eb-9526-5d5a0bfcf1a5.png)

![image](https://user-images.githubusercontent.com/1882836/98300997-655e7780-1fba-11eb-9d82-30ec8df4d72c.png)

**Border four pixels wide, blue** 

![image](https://user-images.githubusercontent.com/1882836/98301093-8c1cae00-1fba-11eb-8bdc-5eb6110ec4ba.png)

![image](https://user-images.githubusercontent.com/1882836/98301133-98a10680-1fba-11eb-81b0-ec59969f9df6.png)

**Border one pixel wide, black**

![image](https://user-images.githubusercontent.com/1882836/98301177-a6568c00-1fba-11eb-8bd0-70339b137b90.png)

![image](https://user-images.githubusercontent.com/1882836/98301192-abb3d680-1fba-11eb-980d-82c0aa55d1b7.png)

**Border two pixels wide, black**

![image](https://user-images.githubusercontent.com/1882836/98301229-b66e6b80-1fba-11eb-972a-27e2d9ec127e.png)

![image](https://user-images.githubusercontent.com/1882836/98301240-bc644c80-1fba-11eb-8859-8e016ae15e87.png)

**Border three pixels wide, black**

![image](https://user-images.githubusercontent.com/1882836/98301269-c8500e80-1fba-11eb-9434-f941933b98f5.png)

![image](https://user-images.githubusercontent.com/1882836/98301287-cede8600-1fba-11eb-8fe2-17e367e5ee97.png)

**Comment by jpwilliams** [comment]
Crikey, @RWeigelt! Thanks this really thorough spread of border examples! 🤩 Never thought I'd get excited about seeing borders. 😀

Bizarrely, I actually really like the chunky 4-pixel blue border, but I'm confident that won't be to everyone's taste!

From your examples I agree with the border being at least 2 pixels; it definitely gets lost if it's only 1. It's a shame as some transparency (meaning the ability to add a shadow) would really help with this. I might do some tests with transparency again and see if I can circumvent the flickering we were experiencing before, as even a chunky black border can get a bit lost.

There's also the possibility to provide the ability to customise the OSD in terms of colours/sizing so people could use whatever border colour/size they want, but there's a balance to be struck between educated recommendations and providing too much customisation. As someone that looks be pretty heavily involved in UX, I'd love to hear your opinion on this!

**Comment by RWeigelt** [comment]
Hi @jpwilliams, with a night's sleep between creating the mockups and looking at them, I'd go with the black, two-pixel border.

I think it's a good compromise:
* It provides good visibility on virtually any background.
* It does not look like an explicit design statement and does not interfere with the design of the OSD.

**Comment by jpwilliams** [comment]
Cool I think I agree - this'll appear in `v2.0.9` along with a couple of bug fixes.

**Comment by jpwilliams** [comment]
Border changed to 2px black in [`v2.0.9`](https://github.com/jpwilliams/midi-mixer-releases/releases/tag/v2.0.9).
