### ISSUE TITLE
RUN with parameters

### ISSUE THREAD

**Issue by pgScorpio** [jpwilliams/midi-mixer-releases#8]
**Is your feature request related to a problem? Please describe and link using # if you can.**

You can't assign a button to run a program with parameters.
Even running a shortcut link just runs the program from the link without parameters. (MIDI Mixer seems to copy the program from the link instead of executing the link itself.)
So you can't open a specific mp3 file, youtube link, etc..

**Describe the solution you'd like**

The ability to specify the program with parameters for "Run file..." or at least run shortcuts and url's using shellexec so the parameters are taken into account.
Also being able to see to which program a "Run file..." button is assigned to would be very nice.

**Describe alternatives you've considered**

The only way I found to bypass this issue is to run batch files which open the required program/shortcut/url. 
This works, but is far from user friendly.

**Additional context**

**Comment by jpwilliams** [comment]
Ah I completely agree on this. Another user brought something similar up in November, so there's a card on the [roadmap](https://roadmap.midi-mixer.com) entitled [Add the ability for faders/buttons to run arbitrary commands with dynamic values](https://trello.com/c/iPya0AbK/33-add-the-ability-for-faders-buttons-to-run-arbitrary-commands-with-dynamic-values).

The idea being discussed there is a little bit different, and this one should be a lot simpler to implement in the short-term if scoped only to the "Run file..." buttons.

Thank you loads for filling out a proper request for this. I've adjusted the card linked above and added a bit more info. In the short term I'm sure I can, at the very least, ensure that shortcuts are handled properly!

**Comment by pgScorpio** [comment]
@jpwilliams Thanks ! Looking forward for the new release wich would include this !

**Comment by jpwilliams** [comment]
Shifting things over slightly, @pgScorpio.

Feature requests/progress will be tracked over on the [roadmap](https://roadmap.midi-mixer.com), so I'll close this in lieu of the linked "Will Implement" roadmap item above.

If you think the roadmap item is missing any crucial details specific to this request, please comment and add it over there! :)
