### ISSUE TITLE
Buttons don't work in midi-mixer with PreSonus Faderport Classic

### ISSUE THREAD

**Issue by wildcat37** [jpwilliams/midi-mixer-releases#9]
**Describe the bug** 
midi-mixer not handling button press on the Faderport device correctly

**To Reproduce**

1. create new controls
2. select type = button
3. click "learn entire control"
4. push a button on the fader port device
5. assign button to mute function to a group
6. assign group to speakers
7. press button, mute function does not work

**Expected behavior**
Expect the function in midi-mixer to work, mute in this case, when button is pushed.

**Build (please complete the following information):**
 - Version v2.21
 
**Additional context**
I have traced the midi messages for the buttons on the Faderport device with pocket midi software. In pocket midi, I see the midi messages when the button is pushed, I can also send midi messages to turn the button LEDs on and off.

When I try to implement the buttons and the LED indicators in midi-mixer, both the buttons and LED indicators don't work. I'm starting to think something is not handled correctly in midi-mixer. Is there anyway to see the midi messages as well as the raw hex values that midi-mixer is sending and receiving?

**Comment by jpwilliams** [comment]
Hi @wildcat37! Thanks for submitting a bug report.

It's possible to see the messages that MIDI Mixer is attempting to send to the board by using [loopMIDI](https://www.tobias-erichsen.de/software/loopmidi.html), but it's not currently possible to see what MIDI Mixer is receiving. To achieve the former, set a loopMIDI port to be the "Output" of a profile, then track that same loopMIDI port within another program such as [Pocket MIDI](https://www.morson.jp/pocketmidi-webpage/).

There's a roadmap item [here](https://trello.com/c/KzYltL2i/27-add-a-midi-log-to-debug-messages-being-sent-by-your-board) to add a log of incoming/outgoing MIDI that may be worth voting for! :)

For this issue, however, could I get you to either paste a screenshot or log of the "MIDI In Monitor" window within Pocket MIDI when you press a button on your Faderport.

My immediate guess is that MIDI Mixer is correctly assigning the message's type, channel, and control, but is failing to use the appropriate velocity.

**Comment by wildcat37** [comment]
Hi,

These are the two midi messages when pressing and releasing the "Record" button on the FaderPort. The first message is the button press, the second is the button release.

A0 07 01
A0 07 00

my understanding is the first midi message is: command=0xA0, data=0x07, data=0x01. where 0xA0 means "after touch, channel 1"


The message required to turn the LED on and off is different from the button push, it is A0 00 01 and A0 00 00 respectively.

**Comment by jpwilliams** [comment]
Thanks, @wildcat37. Yep you're entirely correct on the format.

The last piece of data there in this context will be representative of velocity, meaning my hunch is likely correct too! I had a little look and it seems likely that the handling of `PolyAftertouch` messages was a bit skewed for both input and output, resulting in a failure to either correctly learn or reproduce the given commands.

It'd be fantastic if you could you DM me on [Discord](https://discord.midi-mixer.com) (or just post in the `#support` channel) and I'll get a test build (`v2.2.2-alpha.4`) over to you. It contains a few other fixes and I'd love to release it straight away if it works for you; we haven't yet had a chance to test `PolyAftertouch` messages on a physical device!

**Comment by jpwilliams** [comment]
After working through this with @wildcat37, a number of issues around handling `PolyAftertouch` messages were resolved in [v2.2.2](https://github.com/jpwilliams/midi-mixer-releases/releases/tag/v2.2.2).

There are still some more changes required to enable full use of this device:

1. Sending multiple (high-byte, low-byte) messages for sending and receiving volume changes.
2. Sending a custom message to the device on profile load to push it to an external control mode

The first there we'll treat as a separate issue; this is on my internal list to investigate and implement.
The second will be addressed using device events on the roadmap [here](https://trello.com/c/6r4wH1V6/36-add-events-allowing-a-profile-to-send-specific-midi-commands-in-response-to-events-happening).

I'll close this ticket as this was regarding button issues, but the above two tasks live on and will be addressed!
